name: Build repo

on:
  # when I press the "Run workflow" button in the GitHub UI
  workflow_dispatch:

  # When a PR is opened, sync'd, or reopened
  pull_request:
    types: [opened, synchronize, reopened]
  
  # When a change is pushed to main branch
  push:
    branches:
      - main  
    paths-ignore:
      - '**/*.md'

jobs:

  net6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 6.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  net7:
    needs: net6
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 7.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

  net8:
    needs: net7
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

  sbom:
    needs: [net6, net7, net8]
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate XML SBOM
        uses: CycloneDX/gh-dotnet-generate-sbom@v1
        with:
          path: ./CycloneDX.sln
          github-bearer-token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Generate JSON SBOM
        uses: CycloneDX/gh-dotnet-generate-sbom@master
        with:
          path: ./CycloneDX.sln
          json: true
          github-bearer-token: ${{ secrets.GITHUB_TOKEN }}
